version: '3.8'
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: appsecret
      POSTGRES_DB: filmdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: "cat /proc/net/tcp /proc/net/tcp6 | grep ':0CEB'"
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
